### ISSUE TITLE
two minor fixes to synapse-compress.sh

### ISSUE THREAD

**Issue by jph76** [luki-ev/synod-misc#6]
Hallo Christoph,

I’ve never opened a pull request so I’m choosing this way to fix synapse-compress.sh…

Line 26: `$HOME/bin/synapse-compress-state -t -o /tmp/state-compressor.sql -p "host=$PSQL_HOST user=$PSQL_USER password=$PSQL_PASSWORD dbname=$PSQ_DB" -r "$room" >/dev/null 2>&1`

There’s a typo in `dbname=$PSQ_DB`, this must read `dbname=$PSQL_DB`: `$HOME/bin/synapse-compress-state -t -o /tmp/state-compressor.sql -p "host=$PSQL_HOST user=$PSQL_USER password=$PSQL_PASSWORD dbname=$PSQL_DB" -r "$room" >/dev/null 2>&1`

Line 32: `psql -w -U $PSQL_USER -h $PSQL_HOST --quiet -t -c 'REINDEX DATABASE $PSQL_DB;' $PSQL_DB`

Must use double quotes to make bash expand the `$PSQL_DB` variable: `psql -w -U $PSQL_USER -h $PSQL_HOST --quiet -t -c "REINDEX DATABASE $PSQL_DB;" $PSQL_DB`

Cheers

Jan

**Comment by csett86** [comment]
Thanks for the hint Jan, I have fixed it right away
